spring:
  datasource:
    url: jdbc:mysql://49.232.195.165:3306/java_test
    username: root
    password: 18755138.Bb8487
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

file-save-path: /www/ftpServer/file/

server:
  port: ${port:8083}
  max-http-header-size: 102400

app:
  base: http://127.0.0.1:8083
  appid: wx1a3725c487de09ae
  secret: e45302712ff6f8d73729bd09a8ba583d

logging:
  level:
    org.springframework: DEBUG
    com.hl.vue-we: DEBUG